spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Cr7Imports?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password	

  redis:
    host: localhost
    port: 6379
    password: password

  flyway:
    baselineOnMigrate: true
    enabled: true
    
  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    properties:
      hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.SQLServerDialect.
        show-sql: false
        
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
                
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    servlet:
      path: /apicr7imports

## Actuator
management:
   endpoints:
     web:
       exposure:
         include: 'health,prometheus'
   endpoint:
      health:
        enabled: true
        show-details: always
      prometheus:
        enabled: true				

## Token valido por 1h  
security:
         jwt:
           token:
               expire_length: 3600000
               secret_key: secretGrandeParaQueOGatewayPossaAceitar    

## Swagger
springdoc:
   swagger-ui:
      tags-sorter: alpha
      operations-sorter: alpha	

## Mail
mail:
  config:
     port: 587
     host: smtp.gmail.com
     transport:
         protocol: smtp
     properties:
             mail:
               smtp:
               auth: true  
               starttls:
                 enable: true
     debug: false						 