## Configuração Default da Aplicação ##
server:
   host: localhost
   port: 8761	

## Config Application
spring:
  application:
    name: cr7Discovery

## Eureka - Service Discovery
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://cr7Discovery:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    peer-node-read-timeout-ms: 2000
    peer-node-connect-timeout-ms: 2000