## Configuração Default da Aplicação ##
server:
   host: 0.0.0.0
   port: 8761	

## Config Application
spring:
  application:
    name: cr7Discovery

## Eureka - Service Discovery
eureka:
   host: cr7Discovery
   name: eureka
   port: 8081