spring:

  cloud:
     gateway:
       discovery:
         locator:
            enabled: true  

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/Cr7Imports?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password  

  redis:
    host: localhost
    port: 6379 
    password: password
    
  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    properties:
      hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.SQLServerDialect.
        show-sql: false

server:
   host: localhost
   port: 8888 

## Actuator
management:
   endpoints:
     web:
       exposure:
         include: 'health,prometheus'
   endpoint:
      health:
        enabled: true
        show-details: always
      prometheus:
        enabled: true       

## Token valido por 1h  
security:
         jwt:
           token:
               secret_key: secretGrandeParaQueOGatewayPossaAceitar

## Swagger
springdoc:
   swagger-ui:
      tags-sorter: alpha
      operations-sorter: alpha  

## Application settings
settings:
# Address configuration
    allow-origin: '*'

## Logging level can be one of TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF.     
logging:
    level:
      root: INFO
      com.sistema.cr7ImportsGateway: DEBUG
      io.swagger.models.parameters.AbstractSerializableParameter: DEBUG
      org.hibernate.SQL: DEBUG   

## Eureka - Service Discovery
eureka:
    host: cr7Discovery
    name: eureka
    port: 8081              